  Type: AWS::IAM::Group
  Properties:
    PolicyDocument:  JSON 
    PolicyName: GroupPolicy
  GroupName: Audit
  Path: /
  Policies: 
    - AmazonEc2fullAccess
    - AdministratorAccess


           